// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN0w2Z83VjFMqj4vZwn_738B50GUNjiLE',
    appId: '1:545695743545:web:2ef368af8372bb59bd17e8',
    messagingSenderId: '545695743545',
    projectId: 'chat-app-34808',
    authDomain: 'chat-app-34808.firebaseapp.com',
    storageBucket: 'chat-app-34808.firebasestorage.app',
    measurementId: 'G-Z3T096W4SH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoagcY8JSDEenhPV2dpy2g7jXLnbMUid4',
    appId: '1:545695743545:android:7d8cdc8bcf6258a1bd17e8',
    messagingSenderId: '545695743545',
    projectId: 'chat-app-34808',
    storageBucket: 'chat-app-34808.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeGUkHj668quW97mKUkny3-GuVMfBDKuI',
    appId: '1:545695743545:ios:300c207f20e3316dbd17e8',
    messagingSenderId: '545695743545',
    projectId: 'chat-app-34808',
    storageBucket: 'chat-app-34808.firebasestorage.app',
    iosBundleId: 'com.example.scholarChat2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeGUkHj668quW97mKUkny3-GuVMfBDKuI',
    appId: '1:545695743545:ios:300c207f20e3316dbd17e8',
    messagingSenderId: '545695743545',
    projectId: 'chat-app-34808',
    storageBucket: 'chat-app-34808.firebasestorage.app',
    iosBundleId: 'com.example.scholarChat2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAN0w2Z83VjFMqj4vZwn_738B50GUNjiLE',
    appId: '1:545695743545:web:1ce6d1add7b77a4ebd17e8',
    messagingSenderId: '545695743545',
    projectId: 'chat-app-34808',
    authDomain: 'chat-app-34808.firebaseapp.com',
    storageBucket: 'chat-app-34808.firebasestorage.app',
    measurementId: 'G-0Q9Q301PGS',
  );
}
